version: "3.8"
services:
  php:
    build:
      context: .
      dockerfile: docker-compose/php/Dockerfile
    networks:
      - email_collector
    volumes:
      - ./:/var/www/
    container_name: email-collector-php

  nginx:
    image: nginx:1.17-alpine
    container_name: email-collector-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/:/etc/nginx/conf.d/
    networks:
      - email_collector
    depends_on:
      - php

networks:
  email_collector:
