version: "3.9"
services:
  fpm:
    build:
      context: .
      dockerfile: docker/fpm/Dockerfile
    volumes:
      - "${PWD}:/opt/app"
    container_name: ${BASE_NAME}-fpm

  nginx:
    image: nginx:1.17-alpine
    container_name: ${BASE_NAME}-nginx
    image: ${IMAGE_BASE_NAME}-nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - fpm

networks:
  default:
    name: ${NETWORK}
